Resources:  
  ClaimTable:
    Type: AWS::DynamoDB::Table
    Properties:
      #generate name based on stage
      TableName: ${self:custom.stage}-claims
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: claimId
          AttributeType: S
      KeySchema: 
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: claimId
          KeyType: RANGE
      #set the capicity based on the stage 
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}